In [1]:
print ('gekki!')

gekki!


In [2]:
data = 5
print(data)

5


In [8]:
myPet = {'nama':'eddie',
         'jenis':'kucing',
         'warna':'silver',
         'umur': '1.5',
         'jenis_kelaming':0,
         'vaksin':False}

kelas = {'nama_kelas':'titan',
         'jumlah_murid':15,
         'nama':('rusef','king','rudolf','azura','budiman','venom'),
         'umur':[90.5, 55.1, 80.0, 100, 67.7, 75.7 ],
         'lulus':(True, False, True, True, False, False)}
       

buah = ['apel','mangga','jeruk','pisang','manggis']
jumlah = [10, 5, 15, 6, 21]

gudang = dict(zip(buah,jumlah))

print(myPet)
type(myPet)

print(kelas)
type(kelas)

print(gudang)
type(gudang)


{'nama': 'eddie', 'jenis': 'kucing', 'warna': 'silver', 'umur': '1.5', 'jenis_kelaming': 0, 'vaksin': False}
{'nama_kelas': 'titan', 'jumlah_murid': 15, 'nama': ('rusef', 'king', 'rudolf', 'azura', 'budiman', 'venom'), 'umur': [90.5, 55.1, 80.0, 100, 67.7, 75.7], 'lulus': (True, False, True, True, False, False)}
{'apel': 10, 'mangga': 5, 'jeruk': 15, 'pisang': 6, 'manggis': 21}


dict

In [11]:
gudang.key()
gudang.values()
gudang.items()

AttributeError: 'dict' object has no attribute 'key'

In [17]:
print(gudang)

print('jumlah apel  =', gudang['apel'])
print('jumlah mangga =', gudang['mangga'])
print('jumlah jeruk =', gudang['jeruk'])
print('jumlah pisang =', gudang['pisang'])
print('jumlah manggis =', gudang['manggis'])

{'apel': 10, 'mangga': 5, 'jeruk': 15, 'pisang': 6, 'manggis': 21}
jumlah apel  = 10
jumlah mangga = 5
jumlah jeruk = 15
jumlah pisang = 6
jumlah manggis = 21


In [18]:
print(gudang)

gudang['apel'] = 100

gudang['mangga'] = 150

gudang['pisang'] = 105

gudang['manggis'] = 50

gudang['jeruk'] = 71

print(gudang)

{'apel': 10, 'mangga': 5, 'jeruk': 15, 'pisang': 6, 'manggis': 21}
{'apel': 100, 'mangga': 150, 'jeruk': 71, 'pisang': 105, 'manggis': 50}


In [25]:
print(gudang)

print('jumlah apel =', gudang.get('apel'))
print('jumlah mangga =', gudang.get('mangga'))
print('jumlah jeruk =', gudang.get('jeruk'))
print('jumlah pisang =', gudang.get('pisang'))
print('jumlah manggis =', gudang.get('manggis'))



{'apel': 100, 'mangga': 150, 'jeruk': 71, 'pisang': 105, 'manggis': 50}
jumlah apel = 100
jumlah mangga = 150
jumlah jeruk = 71
jumlah pisang = 105
jumlah manggis = 50


KeyError: slice('apel', 'pisang', None)

In [30]:
print('jumlah jamblang =', gudang.get('jamblang','stock jamblang kosong!'))

jumlah jamblang = stock jamblang kosong!


In [31]:
gudang['ape':'pisang']

KeyError: slice('ape', 'pisang', None)

In [33]:
mahasiswa = {'Nama':'Zee', 'Prodi': 'BD', 'Nilai': [80,100,90]}
print(mahasiswa)

mahasiswa['Nama']

{'Nama': 'Zee', 'Prodi': 'BD', 'Nilai': [80, 100, 90]}


'Zee'

In [40]:
jumlah_buah = {'Apel': 6,
               'Pisang': 12,
               'Jeruk': 10,
               'Jambu Air': 12,
               'Bengkoang': 8,
               'Jambu Biji': 3,
               'Anggur': 10}

jumlah_buah['Stroberi'] = 15
jumlah_buah['Alpukat'] = 12
jumlah_buah['Kelapa'] = 5

print(jumlah_buah)

{'Apel': 6, 'Pisang': 12, 'Jeruk': 10, 'Jambu Air': 12, 'Bengkoang': 8, 'Jambu Biji': 3, 'Anggur': 10, 'Stroberi': 15, 'Alpukat': 12, 'Kelapa': 5}


In [36]:
jumlah_buah['Apel']
jumlah_buah.keys()
jumlah_buah.values()
jumlah_buah.items()

dict_items([('Apel', 6), ('Pisang', 12), ('Jeruk', 10), ('Jambu Air', 12), ('Bengkoang', 8), ('Jambu Biji', 3), ('Anggur', 10), ('Stroberi', 15), ('Alpukat', 12), ('Kelapa', 5)])

In [41]:
print(jumlah_buah)

del jumlah_buah['Kelapa']
print(jumlah_buah, '\n')

pesan = 'Jumlah buah tidak ada!'
jumlah_buah.pop('apel', pesan)

jumlah_buah.clear()
print(jumlah_buah)

{'Apel': 6, 'Pisang': 12, 'Jeruk': 10, 'Jambu Air': 12, 'Bengkoang': 8, 'Jambu Biji': 3, 'Anggur': 10, 'Stroberi': 15, 'Alpukat': 12, 'Kelapa': 5}
{'Apel': 6, 'Pisang': 12, 'Jeruk': 10, 'Jambu Air': 12, 'Bengkoang': 8, 'Jambu Biji': 3, 'Anggur': 10, 'Stroberi': 15, 'Alpukat': 12} 

{}


In [42]:
pesan = 'Jumlah buah tidak ada!'
jumlah_buah.pop('apel', pesan)

'Jumlah buah tidak ada!'

In [43]:
jumlah_buah.clear()
print(jumlah_buah)

{}


In [50]:
import numpy as np

In [ ]:
!pip install numpy

In [61]:
angka = np.array([17, 2, 8, 9 ,7, 5, 4, -1, 0], dtype=int)
print(angka)
type(angka)

[17  2  8  9  7  5  4 -1  0]


numpy.ndarray

In [52]:
alfabet = ['F', 'E', 'N', 'D', 'Y']
alfabet = np.array(alfabet)
print(alfabet)

['F' 'E' 'N' 'D' 'Y']


In [53]:
Suhu = [27.9, 19.2, -1.1, 24.0, 16.0, 22.0, 20.1]
Suhu = np.array(Suhu)
print(Suhu)

[27.9 19.2 -1.1 24.  16.  22.  20.1]


In [62]:
Matriks = np.array([[1,4,1],
                    [2,6,1],
                    [5,1,2]])

print(Matriks)

[[1 4 1]
 [2 6 1]
 [5 1 2]]


In [63]:
A = np.array([[2,8,0], [2,9,0], [-1,2,3]])
A

array([[ 2,  8,  0],
       [ 2,  9,  0],
       [-1,  2,  3]])

In [64]:
image = [[125, 225, 100, 67, 80],
         [100, 200, 112, 80, 92],
         [197, 186, 104, 71, 72],
         [156, 131, 135, 50, 45]]

image = np.array(image, dtype=int)
print(image)
type(image)

[[125 225 100  67  80]
 [100 200 112  80  92]
 [197 186 104  71  72]
 [156 131 135  50  45]]


numpy.ndarray

In [69]:
number = np.array([12, 3, 5, 6, 0, -1, 2])
print(number)
type(number)

[12  3  5  6  0 -1  2]


numpy.ndarray

In [70]:
print(number, '\n')
print('Size         :', number.size)
print('Dimension    :', number.ndim)
print('Shape        :', number.shape, '\n')

print(image, '\n')
print('Size         :',image.size)
print('Dimension    :', image.ndim)
print('Shape        :', image.shape)

[12  3  5  6  0 -1  2] 

Size         : 7
Dimension    : 1
Shape        : (7,) 

[[125 225 100  67  80]
 [100 200 112  80  92]
 [197 186 104  71  72]
 [156 131 135  50  45]] 

Size         : 20
Dimension    : 2
Shape        : (4, 5)


In [71]:
nol_kecil = np.zeros(5)
nol_besar = np.zeros((3,3), dtype=int)

print(nol_kecil, '\n')
print(nol_besar, '\n')

[0. 0. 0. 0. 0.] 

[[0 0 0]
 [0 0 0]
 [0 0 0]] 



In [72]:
vecor_1 = np.ones(10)
matriks_1 = np.ones((4,4), dtype=int)

print(vecor_1, '\n')
print(matriks_1, '\n')

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 



In [73]:
vector_range = np.arange(9)
matriks_range = vector_range.reshape(3,3)

print(matriks_range, '\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

